const express = require("express")
const cors = require("cors")
const {PORT} = require("./config/env")
const Routes = require("./routes")
const dbConnect = require("./config/dbConfig")
dbConnect()
const app = express()
app.use(cors({origin:"*", credentials:true}))
app.use("/api/v1", Routes)
app.listen(PORT,()=>console.log(`app is running on ${PORT}  port`))